### ISSUE TITLE
Where can I download the file "tencent_vocab.txt"?

### ISSUE THREAD

**Issue by yinazhu** [liuwei1206/LEBERT#1]
Hi @liuwei1206 ，Congratulations to your ACL2021 acceptance. Thanks a lot for your work. I was very interested in your research and I'm desired to go through the code to learn more details about your model. 
Can you give me some instructions that provide the addresses for the file "tencent_vocab.txt"?

**Comment by liuwei1206** [comment]
Hi,

Thanks for your interest. 

The tencent_vocab.txt is exactly the vocab table of the pre-trained word embedding.  In other words, you can iterate through the embedding file and saved the contained words as tencent_vocab.txt. Hopes it help.

Wei
