### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MisakaMikoto96** [liuwei1206/LEBERT#13]
when I run run_ner.sh and --do_evaluate I have encountered these kind of problems：

```
Traceback (most recent call last):
  File "Trainer.py", line 598, in <module>
    main()
  File "Trainer.py", line 574, in main
    train(model, args, train_dataset, dev_dataset, test_dataset, label_vocab, tb_writer)
  File "Trainer.py", line 377, in train
    metrics, _ = evaluate(model, args, dev_dataset, label_vocab, global_step, description="Dev", write_file=True)
  File "Trainer.py", line 465, in evaluate
    all_label_ids, all_predict_ids, all_attention_mask, label_vocab)
  File "LEBERT/function/metrics.py", line 40, in seq_f1_with_mask
    tmp_pred.append(label_vocab.convert_id_to_item(all_pred_labels[i][j]).replace("M-", "I-"))
  File "LEBERT/feature/vocab.py", line 84, in convert_id_to_item
    return self.idx2item[id]
IndexError: list index out of range

```

**Comment by liuwei1206** [comment]
Hi,

I don't know which dataset you use so it's hard for me to solve your issue.
I rewrite the run_ner.sh to run_demo.sh, then you can use the demo dataset to evaluate the model. I think it will not have that issue.

Wei

**Comment by s1162276945** [comment]
I met the problem too.

**Comment by s1162276945** [comment]
> when I run run_ner.sh and --do_evaluate I have encountered these kind of problems：
> 
> ```
> Traceback (most recent call last):
>   File "Trainer.py", line 598, in <module>
>     main()
>   File "Trainer.py", line 574, in main
>     train(model, args, train_dataset, dev_dataset, test_dataset, label_vocab, tb_writer)
>   File "Trainer.py", line 377, in train
>     metrics, _ = evaluate(model, args, dev_dataset, label_vocab, global_step, description="Dev", write_file=True)
>   File "Trainer.py", line 465, in evaluate
>     all_label_ids, all_predict_ids, all_attention_mask, label_vocab)
>   File "LEBERT/function/metrics.py", line 40, in seq_f1_with_mask
>     tmp_pred.append(label_vocab.convert_id_to_item(all_pred_labels[i][j]).replace("M-", "I-"))
>   File "LEBERT/feature/vocab.py", line 84, in convert_id_to_item
>     return self.idx2item[id]
> IndexError: list index out of range
> ```



你好，请问你最后解决了吗，我在--do_eval的时候也遇到了，找不到是什么原因导致的。

**Comment by s1162276945** [comment]
weibo/labels.txt has 28 tags and two tags '<pad>' and '<unk>'，add to 30. but pred value contains 31.
=========================================================================

O
B-PER.NOM
E-PER.NOM
B-LOC.NAM
E-LOC.NAM
B-PER.NAM
I-PER.NAM
E-PER.NAM
S-PER.NOM
B-GPE.NAM
E-GPE.NAM
B-ORG.NAM
I-ORG.NAM
E-ORG.NAM
I-PER.NOM
S-GPE.NAM
B-ORG.NOM
E-ORG.NOM
I-LOC.NAM
I-ORG.NOM
B-LOC.NOM
I-LOC.NOM
E-LOC.NOM
B-GPE.NOM
E-GPE.NOM
I-GPE.NAM
S-PER.NAM
S-LOC.NOM

**Comment by s1162276945** [comment]
> when I run run_ner.sh and --do_evaluate I have encountered these kind of problems：
> 
> ```
> Traceback (most recent call last):
>   File "Trainer.py", line 598, in <module>
>     main()
>   File "Trainer.py", line 574, in main
>     train(model, args, train_dataset, dev_dataset, test_dataset, label_vocab, tb_writer)
>   File "Trainer.py", line 377, in train
>     metrics, _ = evaluate(model, args, dev_dataset, label_vocab, global_step, description="Dev", write_file=True)
>   File "Trainer.py", line 465, in evaluate
>     all_label_ids, all_predict_ids, all_attention_mask, label_vocab)
>   File "LEBERT/function/metrics.py", line 40, in seq_f1_with_mask
>     tmp_pred.append(label_vocab.convert_id_to_item(all_pred_labels[i][j]).replace("M-", "I-"))
>   File "LEBERT/feature/vocab.py", line 84, in convert_id_to_item
>     return self.idx2item[id]
> IndexError: list index out of range
> ```

你好，请问你这个问题解决了吗

**Comment by iamlockelightning** [comment]
+1

**Comment by lvjiujin** [comment]
In the crf, why the author add 2 to the tagset_size?
