### ISSUE TITLE
改完transformers的源码，运行shell脚本出现问题

### ISSUE THREAD

**Issue by s1162276945** [liuwei1206/LEBERT#14]
/opt/conda/lib/python3.6/site-packages/transformers-4.7.0.dev0-py3.6.egg/transformers/tokenization_utils_base.py:1631: FutureWarning: Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  FutureWarning,
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'Trainer.py', '--local_rank=0', '--do_train', '--do_eval', '--do_predict', '--evaluate_during_training', '--data_dir=data/dataset/NER/weibo', '--output_dir=data/result/NER/weibo/lebertcrf', '--config_name=data/berts/bert/config.json', '--model_name_or_path=data/berts/bert/pytorch_model.bin', '--vocab_file=data/berts/bert/vocab.txt', '--word_vocab_file=data/vocab/tencent_vocab.txt', '--max_scan_num=100', '--max_word_num=5', '--label_file=data/dataset/NER/weibo/labels.txt', '--word_embedding=data/embedding/word_embedding.txt', '--saved_embedding_dir=data/dataset/NER/weibo', '--model_type=LEBertCRF_Token', '--seed=106524', '--per_gpu_train_batch_size=4', '--per_gpu_eval_batch_size=4', '--learning_rate=1e-5', '--max_steps=-1', '--max_seq_length=256', '--num_train_epochs=2', '--warmup_steps=190', '--save_steps=600', '--logging_steps=600']' died with <Signals.SIGKILL: 9>.

**Comment by liuwei1206** [comment]
Hi,

I think this is caused by the incorrect version of the transformer. You can refer to your log print "FutureWarning: Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.". Please read the log in detail then open an issue.

Wei

**Comment by s1162276945** [comment]
重新安装后，检查版本号是 transformers==3.4.0 ，还是出现
Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated

**Comment by s1162276945** [comment]
in url about transformers/v3.4.0, no BertTokenizer.from_pretrained can be found.

https://huggingface.co/transformers/v3.4.0/search.html?q=from_pretrained&check_keywords=yes&area=default#

**Comment by liuwei1206** [comment]
Hi,

The class "BertTokenizer" is the subclass of "PretrainedTokenizer", which is also a subclass of "PreTrainedTokenizerBase". And you can find the definition of "from_pretrained" in "PreTrainedTokenizerBase".

I am not sure which cause your error since I didn't encounter that. Maybe you should solve it by yourself from the perspective of transformer version and distribution training. Hopes it help.

**Comment by HypnotheKlay** [comment]
> 重新安装后，检查版本号是 transformers==3.4.0 ，还是出现
> Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated

我也遇到同样的问题，请问您解决了吗？

**Comment by s1162276945** [comment]
> > 重新安装后，检查版本号是 transformers==3.4.0 ，还是出现
> > Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated
> 
> 我也遇到同样的问题，请问您解决了吗？

已解决，方法如下：
python install transformers==3.4.0
pip --version 查看site-packages所在目录
进入目录找到 transformers 源码。
进入源码，搜索 beta，修改代码如下：

```python

def _load_state_dict_into_model(cls, model, state_dict, pretrained_model_name_or_path, _fast_init=True):
    # Convert old format to new format if needed from a PyTorch state_dict
    old_keys = []
    new_keys = []
    for key in state_dict.keys():
        new_key = None
        if "gamma" in key:
            new_key = key.replace("gamma", "weight")
        if "beta" in key:
            new_key = key.replace("beta", "bias")
        if "module." in key:
            new_key = key.replace("module.", "")
        if new_key:
            old_keys.append(key)
            new_keys.append(new_key)
```

**Comment by lvjiujin** [comment]
> > > 重新安装后，检查版本号是 transformers==3.4.0 ，还是出现
> > > Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated
> > 
> > 
> > 我也遇到同样的问题，请问您解决了吗？
> 
> 已解决，方法如下： python install transformers==3.4.0 pip --version 查看site-packages所在目录 进入目录找到 transformers 源码。 进入源码，搜索 beta，修改代码如下：
> 
> ```python
> def _load_state_dict_into_model(cls, model, state_dict, pretrained_model_name_or_path, _fast_init=True):
>     # Convert old format to new format if needed from a PyTorch state_dict
>     old_keys = []
>     new_keys = []
>     for key in state_dict.keys():
>         new_key = None
>         if "gamma" in key:
>             new_key = key.replace("gamma", "weight")
>         if "beta" in key:
>             new_key = key.replace("beta", "bias")
>         if "module." in key:
>             new_key = key.replace("module.", "")
>         if new_key:
>             old_keys.append(key)
>             new_keys.append(new_key)
> ```

有邮箱吗？可以交流下吗？
