### ISSUE TITLE
Mac使用intel的cpu跑代码遇到的问题

### ISSUE THREAD

**Issue by WzyPaopao** [liuwei1206/LEBERT#18]
您好，十分感谢您开源该代码。
我在使用MacBook pro 16(16 inch, 2019, intel core-i7) 运行您的代码时，使用 NER/weibo 的 checkpoint 和数据，会出现报错，如下：
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/34997244/123361973-86ec8d80-d5a2-11eb-88bc-1b775b76dd36.png">
请问有什么解决方案吗，十分期待您的回复

**Comment by WzyPaopao** [comment]
补充：我使用的是cpu版本的 pytorch 和 tensorflow

**Comment by liuwei1206** [comment]
Hi,

Have you modified the Transformer as I describe in README? 

From the error info, it seems that there doesn't exist the checkpoint file. So you can check the path of the file.
