### ISSUE TITLE
howboundary_ids

### ISSUE THREAD

**Issue by seyoulala** [liuwei1206/LEBERT#24]

**Comment by seyoulala** [comment]
The boundary_ids is not used by BertEmbedding？

**Comment by liuwei1206** [comment]
Yes. I didn't utilize it now and left it for future study to see if it is useful.

**Comment by liuwei1206** [comment]
According to the paper "Simplify the Usage of Lexicon in Chinese NER", it may be helpful to sequence labeling tasks.
