### ISSUE TITLE
你好，请问方便发一份处理好的Ontonote4.0 Chinese的数据集给我吗？（我已经得到了授权）

### ISSUE THREAD

**Issue by 1737631162** [liuwei1206/LEBERT#30]
你好，我已经得到了LDC的授权：
![截屏2021-09-15 20 58 52](https://user-images.githubusercontent.com/49341242/133443284-6d7ac93b-ce12-492f-bbe8-294ba3e5f02c.png)
但是现在网络上只有Ontonote5.0版本的处理脚本，而Ontonote4.0我不知道该怎么去处理，希望能发一份处理好的Ontonote4.0数据集给我，万分感谢！🙏 （邮箱：s200101190@stu.cqupt.edu.cn）

**Comment by minskiter** [comment]
您好！我最近在做实验对比，但是不知道在该实验中，Ontonote4数据NER是如何进行预处理的。可以发一份处理好给我吗，谢谢您！（已获得Ontonote4许可）（邮箱: 031602243@fzu.edu.cn)
