### ISSUE TITLE
Results all "O" on weibo

### ISSUE THREAD

**Issue by zzysh12345** [liuwei1206/LEBERT#38]
Your work is really amazing!
I am currently learning your code. When I try to train LEBERT on the weibo dataset, I find that the predicted results are all "O" despite that I haven't done any changes to your code. However, using the checkpoint you provide can indeed get good results.
What could be the reason for this? How can I train on my own to get these checkpoints provided by you?
I would be very appreciated if you helped me!

**Comment by lvjiujin** [comment]
> > When training, do you use the stript for Weibo in the Weibo checkpoint?
> 
> Yes, except that I change the model to "pytorch_model.bin" and add "do train"in that I want to train on my own. Moreover, when I try to train on resume, it reaches 90 which is lower than 95 reported. How can I reproduce the checkpoint provided?

I guess the github code is not the author's original code which generates the checkpoint model.
