### ISSUE TITLE
where download the checkpoints?

### ISSUE THREAD

**Issue by dghlnvyps** [liuwei1206/LEBERT#40]
Hello, I have downloaded all the files you provide in the github, but I didn't find the checkpoints. Can you tell how to download it? Providing the links is the best, thank you.

**Comment by dghlnvyps** [comment]
Besides, I don't understand the meaning of this line in the markdown: 'Compile the revised source code and install. python3 setup.py install'. What is the 'setup.py' file is?

**Comment by liuwei1206** [comment]
If you click each named checkpoint, you will redirect to the download link.

Reinstall using compiled method!

**Comment by dghlnvyps** [comment]
Sorry, I do get what you mean of "click each named checkpoint".

I clicked the **Weibo Ner** linking "https://drive.google.com/file/d/1HP-Fc06dMN1jqxoRivLwtAJvQm3MG64Y/view?usp=sharing", and downloaded the file of "weibo.zip". I unziped the file and get the three files: pytorch_model.bin, readme.txt and run_weibo.sh. Do you mean the pytorch_model.bin is the checkpoint file?

**Comment by liuwei1206** [comment]
Yes, you are right!
