### ISSUE TITLE
do_predict问题

### ISSUE THREAD

**Issue by Yesgo1220** [liuwei1206/LEBERT#42]
对torch不太熟悉，请问在只do_predict的时候，没有找到load_state_dict这样的操作，模型是怎么预测的？麻烦指点一二，感谢。作者是否应该在do_predict中加上model.load_state_dict(torch.load(model_name))

**Comment by liuwei1206** [comment]
Hi,

Thanks for your comment. When do evaluation or prediction, I will change the model_name_or_path with the trained checkpoint. In this way, you can load it with load_from_pretrain function.

Best
