### ISSUE TITLE
What's your pretrained model? 

### ISSUE THREAD

**Issue by lvjiujin** [liuwei1206/LEBERT#44]
Hello, I want to ask you what's your pretrained model, bert-base-chinese or bert-wwm? chinese-roberta-wwm? I read your paper, you said bert-base, So I want to know your specific pretrained model.

**Comment by liuwei1206** [comment]
bert-base-chinese. I provide the download link of the pretrained model.

**Comment by lvjiujin** [comment]
> bert-base-chinese. I provide the download link of the pretrained model.

Thank you very much. very good!
