### ISSUE TITLE
腾讯词嵌入向量下载链接失效了

### ISSUE THREAD

**Issue by JiaDuo-Lin** [liuwei1206/LEBERT#45]
腾讯词嵌入向量下载链接失效了

**Comment by liuwei1206** [comment]
Hi, 

Thanks for your information. We have updated it.

Best,
Wei

**Comment by JiaDuo-Lin** [comment]
可以发我一份吗

**Comment by liuwei1206** [comment]
Hi,

The embedding is extremely large, so I recommend you to download it by yourself.
