### ISSUE TITLE
label error

### ISSUE THREAD

**Issue by LMXKO** [liuwei1206/LEBERT#52]
when I run demo，it tell me label 'O' is a error key，
<img width="846" alt="image" src="https://user-images.githubusercontent.com/35209678/165298197-0a879a38-6648-47ed-9652-5be01669d622.png">

**Comment by liuwei1206** [comment]
I am sorry. I don't know the exact reason.

It seems something wrong in dataset reader. I think you can debug and fix it.

Best

**Comment by zlh-source** [comment]
+1

**Comment by t2413** [comment]
i have the same problem, anyone knows how to fix it ?  thanks!
