### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by AnddyWang** [liuwei1206/LEBERT#53]
IndexError: list index out of range，label为【0-28】，提示 29 越界

**Comment by mxa4646** [comment]
Maybe same question https://github.com/liuwei1206/LEBERT/issues/51#issuecomment-1219294423

**Comment by minskiter** [comment]
因为CRF预测额外添加了两个虚标签（开始和结束标签）。训练参数预测出来的标签为虚标签，这是本文作者没有设置两种状态转移为不可转移导致的。
