### ISSUE TITLE
Ontonotes4.0数据集

### ISSUE THREAD

**Issue by GaoYb923** [liuwei1206/LEBERT#54]
您好，
我已获取LDC Ontonotes4.0数据集授权，但自己做分割得到的NER数据集与原作者版本有出入。
可以请问您要一份Ontonotes4.0分割好的数据集吗？仅做个人研究使用。
我的邮箱是gaoyunbo923@buaa.edu.cn
如需验证LDC授权请联系我
祝一切顺利

**Comment by liuwei1206** [comment]
Please check your email.
