### ISSUE TITLE
您提供的NER数据页面打不开

### ISSUE THREAD

**Issue by bjyx-star** [liuwei1206/LEBERT#56]
* [Weibo NER](https://drive.google.com/file/d/1HP-Fc06dMN1jqxoRivLwtAJvQm3MG64Y/view?usp=sharing)
* [Ontonote4 NER](https://drive.google.com/file/d/1Tr_G-aK32cCfeJXd8f3mAU9reo-KHRKu/view?usp=sharing)
* [MSRA NER](https://drive.google.com/file/d/1QsTiTPovvrhQ-xxSbRh9DV45-svCcWNH/view?usp=sharing)
* [Resume NER](https://drive.google.com/file/d/1ES8uMSAq3pE8MRpiOBKYNWr0qXq9j93r/view?usp=sharing)

**Comment by liuwei1206** [comment]
Hi, 

they are pages to download checkpoints. You don't need to open them but just click the download button.
