### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 'C:\\LEBERT-main\\data\\log\\wcbert_token_file_2022-11-20_19:46:58.txt'

### ISSUE THREAD

**Issue by bjyx-star** [liuwei1206/LEBERT#57]

**Comment by liuwei1206** [comment]
Sorry. I won't reply to any issues before you have read the code carefully. If you have read the code, you will find this is a very simple setting.

Regards.

**Comment by YMXBL** [comment]
Windows系统需要把路径中的“:”，换成其他符号。
Windows system needs to replace the ":" in the path with other symbols.
