### ISSUE TITLE
关于setup.py

### ISSUE THREAD

**Issue by zlh-source** [liuwei1206/LEBERT#58]
你好，README里写的“Compile the revised source code and install. python3 setup.py install”
但是仓库里没有setup.py文件，请问应该怎么安装？

**Comment by liuwei1206** [comment]
Hi,

There should be a setup.py in source/transformers-master. Please follow my transformer version and re-check it. 

Running "python3 setup.py install" means you re-install the revised version of transformers.

**Comment by zlh-source** [comment]
OK, thank you very much.
I will try again.
