### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Victor-xx** [liuwei1206/LEBERT#59]
Hello, can you send me the PKU, MSR and CTB6 datasets of the Chinese Word Segmentation task and the CTB5, CTB6, UD1 and UD2 datasets of the Chinese POS Tagging task by email? My email is 2428351898@qq.com Thank you very much.

**Comment by liuwei1206** [comment]
Hi, please check your email.

**Comment by t2413** [comment]
您好，可以给我也发一份吗？比较急用。这是我的邮箱 928417409@qq.com  十分感谢！
