### ISSUE TITLE
trainner can not support LEBertCRF_Token model type

### ISSUE THREAD

**Issue by wj-Mcat** [liuwei1206/LEBERT#6]
when I prepare all of dataset, and run `./run_ner.sh`, it will throw the error: 

```shell
Traceback (most recent call last):
  File "Trainer.py", line 593, in <module>
    main()
  File "Trainer.py", line 552, in main
    model = model.cuda()
UnboundLocalError: local variable 'model' referenced before assignment
Traceback (most recent call last):
  File "/home/human/miniconda3/envs/qzqExp/lib/python3.7/runpy.py", line 193, in _run_module_as_main
```
After checking the code, it's:

https://github.com/liuwei1206/LEBERT/blob/main/Trainer.py#L537-L550

there is no 'LEBertCRF_Token' in Trainner.

**Comment by wj-Mcat** [comment]
It sees Lexcion Adpater has been applied into `BertLayer` which means `WCBertCRFForToken` is already great for model.

**Comment by liuwei1206** [comment]
Hi, 

In my code, you should set the variable model_type to "WCBertCRF_Token" or "BertWordLSTMCRF_Token". And "WCBertCRF_Token" just means "LEBERTCRF".  

This is an old version of my implementation so I didn't update the name of some variables. If you prefer the name "LEBertCRF_Token", you can change it in the Trainer.py at line 537.

Wei

**Comment by wj-Mcat** [comment]
Thanks for your explanation, I got it. By the way, can you commit your latest experiment code so that we can it more effciently.

**Comment by liuwei1206** [comment]
Hi,

They are very same and just differ from some model names and variable names. I did not plan to update it because the code is already clear enough. I strongly recommend you read the source code. It may be very helpful.

Wei

**Comment by wj-Mcat** [comment]
Ok, I will read it later. Thanks for your contribution .
