### ISSUE TITLE
saved_maxword_5_maxseq_48_NER\\train_10000.npz文件不存在？

### ISSUE THREAD

**Issue by yys-1** [liuwei1206/LEBERT#60]
FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset\\saved_maxword_5_maxseq_48_NER\\train_10000.npz'

**Comment by mingcheng0813** [comment]
同问，这个问题怎么解决啊？

**Comment by mingcheng0813** [comment]
please help me solve this issue

**Comment by mingcheng0813** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset\saved_maxword_5_maxseq_48_NER\train_10000.npz'

换一文件名就可以了。比如：train.npz
