### ISSUE TITLE
Ontonotes4.0数据集

### ISSUE THREAD

**Issue by doushabao7466** [liuwei1206/LEBERT#62]
您好，
我已获取LDC Ontonotes4.0数据集授权，但是处理出来结果有点不对。
可以请问您要一份Ontonotes4.0分割并处理好的数据集吗？仅做个人研究使用。
我的邮箱是caifs@my.swjtu.edu.cn
如需验证LDC授权请联系我
祝一切顺利

**Comment by liuwei1206** [comment]
Hi,

Please check it.
