### ISSUE TITLE
Question about the size [N, L, W, D]

### ISSUE THREAD

**Issue by JubSteven** [liuwei1206/LEBERT#64]
Hi, thanks for your great work! I want to ask a question about the size of the tensor during the pipeline. According to the paper, for a sentence (or a phase) like "美国人民", it is first segmented into words like "美国", "美国人", "国人", etc. For each segmented word, we sort of add the word vector to each corresponding character of the word.

But in this way, how do we make sure that the dimension W is fixed? For example, the word "美" might have two words  "美国", "美国人" accompanied with it, while "民" only has one word "人民".

Thanks for your patience!

**Comment by huskydoge** [comment]
same issue

**Comment by liuwei1206** [comment]
Hi,

I am sorry to say that I kind of forgot the details. In my memory, the W seems to be a hyper-parameter. If a character has a matched word number less than W, then we can use padding. 

Hope it helps.

**Comment by JubSteven** [comment]
Ok, thanks!
