### ISSUE TITLE
请问实验结果是训练完成之后，直接运行测试集得到的结果吗？

### ISSUE THREAD

**Issue by Haojunzuo** [liuwei1206/LEBERT#65]
您好，非常感谢您开源代码，我看到您的代码中，并没有在dev数据集上取最好结果时保存模型，请问您获取最终实验数据的方式是什么呢？是直接在训练20个epoch之后，直接运行测试集返回结果吗？

**Comment by liuwei1206** [comment]
First, pick out the epoch where the model achieves the best performance on the dev set;
Second, get the model's performance on the test set.
