### ISSUE TITLE
There are some undefined variables and objects

### ISSUE THREAD

**Issue by Single430** [liuwei1206/LEBERT#7]
A great job, thank you for sharing it publicly, but has the author of this project run it? Because i have a lot of problems.
I have run the code, but need to be changed, not friendly to newcomers.

wcbert_modeling.py
line 455: BaseModelOutputWithPooling
line 531:  word_pooling_type

Trainer.py
line 197
line 278~314

![IMG_20210605_105822.jpg](https://user-images.githubusercontent.com/7894408/120878121-f814d280-c5ec-11eb-8078-99cd1b25cb74.jpg)

**Comment by liuwei1206** [comment]
Hi,

Thanks for your feedback. I have run it and it works well. This is not all the code about the paper but only the implementation of the proposed model. So there are some undefined variables and objects. I will check it and delete some unused variables and objects.

Wei
