### ISSUE TITLE
Can the datasets be shared to other cloud disks?

### ISSUE THREAD

**Issue by Single430** [liuwei1206/LEBERT#8]
Hi.Rt

Thx

**Comment by 1065283526** [comment]
我下载了，留个邮箱我发给你

**Comment by liuwei1206** [comment]
@1065283526, thanks for your share!

**Comment by Single430** [comment]
> 我下载了，留个邮箱我发给你

非常感谢，3057307263@qq.com

**Comment by MisakaMikoto96** [comment]
> 我下载了，留个邮箱我发给你

您好，非常感谢，可以发我一份吗 493594703@qq.com 感激不尽
